### ISSUE TITLE
flans aircraft issue

### ISSUE THREAD

**Issue by Draknashaw** [skittishtrigger/TechnAintEasy#4]
alright skits iv made my chinook iv planted over at huus place mainly for room iv fueled the heilo and took off on a set coarse for my cliffside house. quarter of the way to my destination i FALL OUT OF THE FUCKING CHOPPER. i didnt not hit any keys with the exception of the W to asend key i just fall unable to move hit or anything. after i shift to escape i find myself falling out of the chopper again this time dieing when i hit the ground. pleeease look into this and fix this.

**Comment by skittishtrigger** [comment]
This sounds like a client/server syncing issue for packets. Further investigation and testing needed.

**Comment by skittishtrigger** [comment]
Update

http://speedof.me/   <--use this test. after done click share and link url here.
http://www.pingtest.net/  <--here too. Run test then click direct link and paste url here.

**Comment by Draknashaw** [comment]
1# Download Speed: 32.08 Mbps
Upload Speed: 12.86 Mbps

ping 31
jitter 16  


and what of the materials i used to perform this aircraft test?

**Comment by skittishtrigger** [comment]
Those are not links.........This is for issues not refunds....

**Comment by skittishtrigger** [comment]
ii can not reproduce this issue and with no more updates and previous 1 on 1 ts'ing I am closing this issue on the grounds of 32bit os/java and improper setup/client cooperation.
